config/routes.rb
Rails.application.routes.draw do

  resources :profiles

  get 'friendships/newcreate'

  get 'friendships/destroy'

  root 'welcome#index'
  resources :posts do
    resources :comments
    resources :likes
  end

  get 'users/index'

  devise_for :views
  get 'welcome/index'
  devise_for :users, :controllers => {:registrations => "devise/registrations"} do
  get '/register' => 'devise/registrations#new', :as => :new_user_registration
  end
  resources :users
  resources :friendships

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
   post_id = params[:post_id]
   @post = Post.find_by(id: post_id)
    @like = current_user.likes.build(post_id: post_id)
    if @like.save
      flash[:notice] = "You like the post #{@post.title}."
    else
      flash[:error] = "There was an error liking the post #{@post.title}."
    end

    respond_to do |format|
      format.html
      format.js
    end
  end
  def destroy
    post_id = params[:post_id]
    @post = Post.find_by(id: post_id)
    @like = @post.likes.find(params[:id])
    if @like.destroy
      flash[:notice] = "You have unliked the #{@post.title} post"

    else
      flash[:error] = "There was an error unliking the post #{@post.title}"

    end
    respond_to do |format|
      format.html
      format.js
    end
  end
  private
  def likes_params
    params.require(:like).permit(:post_id)
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_create.html.haml
= link_to "Like", post_likes_path(post_id: @post.id),remote:true, method: :post

app/views/likes/_delete.html.haml
= link_to "Unlike", post_like_path(post_id: @post.id ,id: @like.id), remote: true, method: :delete

app/views/likes/_like.html.haml
.likes
  - if @like.blank?
    = render partial:'likes/create'
  - else
    = render partial: 'likes/delete'

app/views/likes/create.js.erb
$('.likes').html("<%= escape_javascript(render partial: 'likes/delete') %>");

app/views/likes/destroy.js.erb
$('.likes').html("<%= escape_javascript(render partial: 'likes/create' ) %>");