config/routes.rb
Rails.application.routes.draw do

  resources :profiles

  get 'friendships/newcreate'

  get 'friendships/destroy'

  root 'welcome#index'
  resources :posts do
    resources :comments
    resources :likes
  end

  get 'users/index'

  devise_for :views
  get 'welcome/index'
  devise_for :users, :controllers => {:registrations => "devise/registrations"} do
  get '/register' => 'devise/registrations#new', :as => :new_user_registration
  end
  resources :users
  resources :friendships

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  def user
    User.find(self.user_id)
  end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class: 'User', foreign_key: 'friend_id'
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :likes
  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  has_one :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
  has_many :friendships
  has_many :friends, through: :friendships
  has_many :likes
  has_one :profile
  def visible_posts
    posts = []
    posts << Post.where(user_id: self.id)
    friendships.each do |friend|
      posts << Post.where(user_id:friend.friend_id)
    end
    posts.flatten!.uniq!
    posts
  end
  def friends
    frends = []
    friendships.each do |friend|
      frends << User.find(friend.friend_id)
    end
    frends.flatten!
    frends.uniq!
    frends
  end
  def profile
    Profile.find_by(user_id:self.id)
  end
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
   @comments = @post.comments
   @comment = current_user.comments.build( comment_params )
   @comment.post = @post
  

   if @comment.save
     flash[:notice] = "Comment was created."
   else
     flash[:error] = "There was an error saving the comment. Please try again."
   end

   respond_to do |format|
     format.html
     format.js
   end
  end

  def destroy


    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

    if @comment.destroy
      flash[:notice] = "Comment was removed."

    else
      flash[:error] = "Comment couldn't be deleted. Try again."

    end

    respond_to do |format|
     format.html
     format.js
    end
  end
  private

   def comment_params
     params.require(:comment).permit(:content)
   end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
   post_id = params[:post_id]
   @post = Post.find_by(id: post_id)
    @like = current_user.likes.build(post_id: post_id)
    if @like.save
      flash[:notice] = "You like the post #{@post.title}."
    else
      flash[:error] = "There was an error liking the post #{@post.title}."
    end

    respond_to do |format|
      format.html
      format.js
    end
  end
  def destroy
    post_id = params[:post_id]
    @post = Post.find_by(id: post_id)
    @like = @post.likes.find(params[:id])
    if @like.destroy
      flash[:notice] = "You have unliked the #{@post.title} post"

    else
      flash[:error] = "There was an error unliking the post #{@post.title}"

    end
    respond_to do |format|
      format.html
      format.js
    end
  end
  private
  def likes_params
    params.require(:like).permit(:post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
    @like = Like.find_by(post_id: @post.id, user_id: current_user.id)

  end
  def edit
    @post = Post.find(params[:id])
  end
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:notice] = "Post was saved."
      redirect_to posts_path
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end
  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(post_params)
      flash[:notice] = "Post was updated"
      redirect_to posts_path
    else
      flash[:error] = "Invalid Post information"
      render :edit
    end
  end
  def destroy
    @post = Post.find(params[:id])
    

    if @post.destroy
      flash[:notice] = "\"#{@post.title}\" was deleted successfully."
      redirect_to posts_path
    else
      flash[:error] = "There was an error deleting the post."
      render :show
    end
  end
  def new
    @post = Post.new
  end
  def index
    @posts = current_user.visible_posts

  end
  private

  def post_params
    params.require(:post).permit(:title, :body, :image, :image_cache)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
def create
   User.create!(user_params)
 end
 def update
   redirect_to current_account.users.find(params[:id]).tap { |user|
     person.update!(user_params)
   if current_user.update_attributes(user_params)
     flash[:notice] = "User information updated"
     redirect_to edit_user_registration_path
   else
     flash[:error] = "Invalid user information"
     redirect_to edit_user_registration_path
   end
 }
end
  def show
    @user = User.find(params[:id])
    
  end

  def index
  end
  private

 def user_params
   params.require(:user).permit(:name)
 end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Friend Book
    %meta{:content => "width=device=width, initial-scale=1", :name => "viewport"}
      = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
      = javascript_include_tag 'application', 'data-turbolinks-track' => true
      = csrf_meta_tags
  %body
    .container
      %ul.nav.nav-tabs
        %li= link_to "Home", root_path
        %li= link_to "Posts", posts_path
        - if current_user.present?
          - if current_user.profile
            %li= link_to "Edit my profile", edit_profile_path(current_user.profile)
          - else
            %li= link_to "Make a profile", new_profile_path
        .pull-right.user-info
          - if current_user
            Hello #{link_to (current_user.name || current_user.email), current_user}!
            = link_to edit_user_registration_path, class: 'btn btn-primary btn-sm' do
              %span.glyphicon.glyphicon-user
            = link_to destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-sm' do
              %span.glyphicon.glyphicon-log-out
          - else
            = link_to "Sign In", new_user_session_path
            = link_to "Sign Up", new_user_registration_path
      - if flash[:notice]
        .alert.alert-success
          %button.close{"data-dismiss" => "alert", :type => "button"} &times;
          = flash[:notice]
      - elsif flash[:error]
        .alert.alert-danger
          %button.close{"data-dismiss" => "alert", :type => "button"} &times;
          = flash[:error]
      - elsif flash[:alert]
        .alert.alert-warning
          %button.close{"data-dismiss" => "alert", :type => "button"} &times;
          = flash[:alert]
      = yield